export enum MSTagType {
    AutoTag = 1,
    ManualTag,
    SearchTag,
}

export enum MSSeoReferenceType {
    Need = 1,
    Area,
    Floor,
    Units,
    Facade,
    Source,
    Access,
    VipType,
    Feature,
    Balcony,
    Bedroom,
    Deposit,
    NeedBuy,
    NeedSell,
    Bathroom,
    UnitArea,
    Utilities,
    Equipment,
    Furniture,
    WideRoads,
    UserTypes,
    WaterUnit,
    UnitPrice,
    EnergyUnit,
    Directions,
    Advantages,
    UnitLength,
    LegalPaper,
    TotalPrice,
    Reputation,
    NeedLiteSell,
    TypeOfHouses,
    BusinessDates,
    BusinessTimes,
    PerCommission,
    PaymentPeriod,
    UnitRentPrice,
    StatusArticle,
    ApprovalContent,
    TypeOfRealEstate,
    LevelTransaction,
    BalconyDirection,
    MinimumRentalPeriod,
}